apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stagging
# Generate ConfigMap dari file index.html
configMapGenerator:
  - name: httpd-index
    files:
      - index.html
generatorOptions:
  disableNameSuffixHash: false  # hash otomatis untuk setiap perubahan

resources:
  - deployment.yaml
  - service.yaml
