apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: stagging
spec:
  type: NodePort
  selector:
    app: simple-httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
