apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: stagging
spec:
  type: NodePort
  selector:
    app: simple-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
